stack: kontena/stolon
version: 0.1.0
description: PostgreSQL cluster for high-availability
expose: proxy
variables:
  affinity:
    type: string
    default: label!=no-stolon
    from:
      prompt: Affinity
  repl_password:
    type: string
    from:
      vault: ${STACK}-repl-password
      random_string: 24
    to:
      vault: ${STACK}-repl-password
  su_password:
    type: string
    from:
      vault: ${STACK}-su-password
      random_string: 24
    to:
      vault: ${STACK}-su-password
services:
  keeper:
    image: sorintlab/stolon:v0.6.0-pg9.6
    stateful: true
    instances: 3
    command: /bin/sh -c "mkdir -p $$STOLON_DATA && chown stolon:stolon $$STOLON_DATA && STKEEPER_PG_LISTEN_ADDRESS=$(hostname -i) STKEEPER_UID=\"keeper_$${KONTENA_SERVICE_INSTANCE_NUMBER}\" gosu stolon stolon-keeper --data-dir $$STOLON_DATA"
    affinity:
      - {{ affinity }}
    secrets:
      - secret: ${STACK}-repl-password
        name: STKEEPER_PG_REPL_PASSWORD
        type: env
      - secret: ${STACK}-su-password
        name: STKEEPER_PG_SU_PASSWORD
        type: env
    environment:
      STKEEPER_CLUSTER_NAME: ${STACK}
      STKEEPER_STORE_BACKEND: etcd
      STKEEPER_STORE_ENDPOINTS: http://etcd.kontena.local:2379
      STKEEPER_PG_REPL_USERNAME: repluser
      STKEEPER_PG_SU_USERNAME: stolon
      STKEEPER_LISTEN_ADDRESS: "0.0.0.0"
      STOLON_DATA: /data/stolon
    hooks:
      post_start:
        - name: init
          cmd: sleep 10 && stolonctl init --cluster-name $$STKEEPER_CLUSTER_NAME --store-backend $$STKEEPER_STORE_BACKEND --store-endpoints $$STKEEPER_STORE_ENDPOINTS -y
          instances: 1
          oneshot: true
    volumes:
      - keeper:/data

  sentinel:
    image: sorintlab/stolon:v0.6.0-pg9.6
    command: gosu stolon stolon-sentinel
    instances: 3
    affinity:
      - {{ affinity }}
    environment:
      STSENTINEL_CLUSTER_NAME: ${STACK}
      STSENTINEL_STORE_BACKEND: etcd
      STSENTINEL_STORE_ENDPOINTS: http://etcd.kontena.local:2379
    depends_on:
      - keeper

  proxy:
    image: sorintlab/stolon:v0.6.0-pg9.6
    command: gosu stolon stolon-proxy
    instances: 3
    affinity:
      - {{ affinity }}
    deploy:
      wait_for_port: 5432
    environment:
      STPROXY_CLUSTER_NAME: ${STACK}
      STPROXY_STORE_BACKEND: etcd
      STPROXY_STORE_ENDPOINTS: http://etcd.kontena.local:2379
      STPROXY_LISTEN_ADDRESS: "0.0.0.0"
    depends_on:
      - keeper
      - sentinel

volumes:
  keeper:
    external:
      name: ${STACK}-keeper